cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

language: scala
scala:
  - 2.12.8
jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION! test

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
